#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NZ_Politics_Bulletin.Resource", IsApplication=true)]

namespace NZ_Politics_Bulletin
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int spashscreenimage = 2130771969;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int Image = 2130837504;
			
			// aapt resource value: 0x7F020003
			public const int imageViewSplash = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int lstNews = 2130837508;
			
			// aapt resource value: 0x7F020001
			public const int Text1 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Text2 = 2130837506;
			
			// aapt resource value: 0x7F020005
			public const int webView1 = 2130837509;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int CustomRow = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int NewsArticle = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int SplashScreenLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
